name: Audit

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          # mise uses GITHUB_TOKEN to interact with the GitHub API when installing
          # tools. This results in a 401 Unauthorized error if the action runs
          # outside of GitHub's infrastructure. As a workaround, only provide
          # GITHUB_TOKEN when running on github.com.
          GITHUB_TOKEN: ${{github.server_url == 'https://github.com' && github.token || ''}}

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Check Licenses
        uses: onlyoffice/check-licenses@v1
        with:
          project_license: MIT

      - name: Build Package
        run: pnpm build

      - name: Lint Package
        run: pnpm lint
